
# this works with the gnu make tool. 
# If you are working with windows, please install cygwin to get
# gnumake (goto http://www.sourceware.cygnus.com).

ROOT=../../../../

-include  $(ROOT)/build-config


all: 
	$(JAVAC) *.java

clean: emacsclean
	\rm -f *.class

