

ROOT=../../

-include $(ROOT)/build-config

clean:
	$(shell find gov -name "*.html" -print -exec rm {} \;)
	$(shell find javax -name "*.html" -print -exec rm {} \;)
	$(shell find class-use -name "*.html" -print -exec rm {} \;)
	$(shell find index-files -use -name "*.html" -print -exec rm {} \;)
	$(RM)  allclasses-frame.html
	$(RM)  allclasses-noframe.html
	$(RM)  constant-values.html
	$(RM)  deprecated-list.html 
	$(RM)  sdp_announceParser.html  
	$(RM)  serialized-form.html  
	$(RM)  overview-*.html 
	$(RM)  help-doc.html
	$(RM)  packages.html
	$(RM)  stylesheet.css 
	$(RM)  index.html 
	$(RM)  package-list
