

ROOT=../../

-include $(ROOT)/build-config

clean:
	$(RM) -rf gov
	$(RM) -rf javax
	$(RM)  -rf index-files
	$(RM)  -rf class-use
	$(RM)  allclasses-frame.html
	$(RM)  allclasses-noframe.html
	$(RM)  constant-values.html
	$(RM)  deprecated-list.html 
	$(RM)  sdp_announceParser.html  
	$(RM)  serialized-form.html  
	$(RM)  overview-*.html 
	$(RM)  help-doc.html
	$(RM)  packages.html
	$(RM)  stylesheet.css 
	$(RM)  index.html 
	$(RM)  package-list
