

ROOT=../../

-include $(ROOT)/build-config

clean:
	\rm -rf  gov
	\rm  -rf jain
	\rm  -rf javax
	\rm  -f  allclasses-frame.html
	\rm  -f  allclasses-noframe.html
	\rm  -f  constant-values.html
	\rm  -f  deprecated-list.html 
	\rm  -f  sdp_announceParser.html  
	\rm  -f  serialized-form.html  
	\rm  -f  overview-*.html 
	\rm  -f  help-doc.html
	\rm  -rf index-files
	\rm  -f  packages.html
	\rm  -f  stylesheet.css 
	\rm  -f  index.html 
	\rm  -f  package-list
