/*******************************************************************************
* Product of NIST/ITL Advanced Networking Technologies Division (ANTD)         *
*******************************************************************************/
package gov.nist.javax.sip.parser;
import gov.nist.javax.sip.message.*;

/**
 * Interface  that provides methods for processing good 
 * and bad messages for the PipelinedMessageParser.
 * 
 * @version JAIN-SIP-1.1 $Revision: 1.4 $ $Date: 2004-01-22 13:26:32 $
 * @see PipelinedMsgParser
 */
public interface SIPMessageListener extends ParseExceptionListener {
	/**
	 * This is called from the parser on successful message processing.
	 * @see ParseExceptionListener for the method that gets called 
	 *	on parse exception.
	 * @param msg  SIP Message structure that is generated by the parser.
	 */
	public void processMessage(SIPMessage msg);
}
/*
 * $Log: not supported by cvs2svn $
 */
